### ISSUE TITLE
Multer setup

### ISSUE THREAD

**Issue by divanvb** [dalenguyen/rest-api-node-typescript#1]
H, can you maybe help me in setting up multer? I'm not sure where to add the middleware to the route where I want to use it. If you need code let me know but I can't seem to get it to work.

**Comment by dalenguyen** [comment]
Yes @divanvb, please share what you did. And I will see what I  can do to help.

**Comment by divanvb** [comment]
@dalenguyen I've managed to fix the issue with uploading a file thanks. Another one I have now is setting up passport and getting the req.user to tell me if the user is authenticated. Can you help with that or should I create a new issue for it?

**Comment by dalenguyen** [comment]
I saw that you create another issue, so I will close this one.
