### ISSUE TITLE
A doubt of structure

### ISSUE THREAD

**Issue by IngAjVillalon** [dalenguyen/rest-api-node-typescript#10]
Sorry to open this issue but it is the only way that I found to communicate with you.
I have a question about how to chain the routes of another feature beautifully.

For example, I have seen that many programmers use this form a lot:
 app.use ('/ api / genres', genres);
  app.use ('/ api / customers', customers);
  app.use ('/ api / movies', movies);
  app.use ('/ api / rentals', rentals);
  app.use ('/ api / users', users);
  app.use ('/ api / auth', auth);
  app.use ('/ api / returns', returns);

where the second value is an express router

How could I do this to make it look nice in [crmRoutes.ts](https://github.com/dalenguyen/rest-api-node-typescript/blob/master/lib/routes/crmRoutes.ts) so that it looks beautiful and clean?

**Comment by sidzan** [comment]
I also stumbled upon the same thing, anyone able to achieve this? 
I wanted to route /v1 to a v1 folder and /v2 to a v2 folder.

**Comment by gsahadevan** [comment]
@IngAjVillalon - try checking this [code](https://github.com/gsahadevan/spend-meter-backend). i have some how managed to get this working. don't know if this is exactly what you are looking for.

**Comment by dalenguyen** [comment]
Sorry for the late reply. There is a way that you can manage the prefix of the path. 

```
const api = express.Router()

api.get('/genres,  geners)
api.get('/customers,  customers)
...
app.use('/api, api)
```

That's all you need.
