### ISSUE TITLE
Unexecutable code: Cannot assign to 'Promise' because it is a read-only 

### ISSUE THREAD

**Issue by Tanja-4732** [dalenguyen/rest-api-node-typescript#11]
The following line of code causes this error to occur:

https://github.com/dalenguyen/rest-api-node-typescript/blob/3e1ad72b6e6d936a73c33c1a66fedec1a424fee9/lib/app.ts#L28

>Cannot assign to 'Promise' because it is a read-only property.ts(2540)

**Comment by Tanja-4732** [comment]
# Update

[aziz salamanki](https://medium.com/@azizsalamanki_31796) said [here](https://medium.com/@azizsalamanki_31796/with-a-new-version-of-mongo-the-syntax-changed-from-mongoose-promise-763324bf22c2) (quote):
with a new version of mongo the syntax changed from :
```JS
mongoose.Promise = global.Promise 
```
 to
```JS
require(‘mongoose’).Promise = global.Promise
```

(end quote)

Is there a way to do this without using `require()`?

**Comment by alshoja** [comment]
### Try this after adding types
`import * as mongoose from 'mongoose';
`


      `mongoose.connect(this.mongoUrl, { useNewUrlParser: true, useUnifiedTopology: true })
      .then(res => { console.log('mongodb connected') })
      .catch(err => { console.log('mongo error in connection:', err) });`
