### ISSUE TITLE
 Type 'typeof e' has no call signatures.ts(2349)

### ISSUE THREAD

**Issue by gongxic** [dalenguyen/rest-api-node-typescript#15]
this is not your project error.When I learn express, I copy your code in my project , and then I get the erorr.and I can fix it by myself,but I can't understant why in your project is ok.Can you help me to telling why? 
![image](https://user-images.githubusercontent.com/1868626/84336753-8917c000-abca-11ea-89d3-72f837e7cb1b.png)

**Comment by dalenguyen** [comment]
Hi @gongxic it's maybe because we have different versions of express & typescript.

**Comment by gongxic** [comment]
@dalenguyen , I will try to update  the versions . thank you very much.
