### ISSUE TITLE
Passport JS setup with typescript and routes middleware

### ISSUE THREAD

**Issue by divanvb** [dalenguyen/rest-api-node-typescript#2]
Hi

I'm having issues with getting certain functions to work. I can register & login using passport just fine. The problem I'm having is if someone is making a request and I want to check "req.user" || "req.isAuthenticated()"

I'm also using passport-local-mongoose for only local authentication.

Any help will be gladly appreciated!

SO Question: https://stackoverflow.com/questions/51180231/issue-with-connect-mongo-passport-passport-local-mongoose-with-session-no-pre

**Comment by dalenguyen** [comment]
Thanks @divanvb, I will take a look at the passport integration over the weekend.

**Comment by dalenguyen** [comment]
Hi @divanvb, I saw that you found a solution. Did it solve your problem?
