### ISSUE TITLE
Cannot find moduel "app" error 

### ISSUE THREAD

**Issue by themese** [dalenguyen/rest-api-node-typescript#3]
Firstly thanks for your tutorial and also sorry if this is not the place to post this, as this is more a question rather than an issue.

So if you use the import statement in the server.ts file as follows:
`import app from "./app"; `
It will pick the export reference from your app.ts file, everything works fine.

On the other hand if you use:
`import app from "app"; `
VSCode will be able to pick the reference from the app.ts and is able to tell you that your import app is correctly imported and is able to trace back where does it come from, but the typescript compiler (probably correctly) fails as it's not able to find the module "app".

Why is this happening, what piece of knowledge am I missing?

Thanks and again sorry if this is not the place to post this.

**Comment by dalenguyen** [comment]
Hi @themese, without './', it will think that you are importing from a node module. You better put the './', so it will look into your current folder.

**Comment by themese** [comment]
Hmm that´s what I thought, but then VSCode is picking the reference properly.
In any case, thanks for the answer, that makes total sense!

**Comment by dalenguyen** [comment]
You're welcome :)
