### ISSUE TITLE
How to apply API prefix

### ISSUE THREAD

**Issue by nbxtruong** [dalenguyen/rest-api-node-typescript#5]
Hello dalenguyen,

I want to apply '/api/v1' prefix to your API, but I do not know how to do it. Can you help me? 

Thank

**Comment by dalenguyen** [comment]
Hi @nbxtruong, sorry I just went back from vacation. You can edit the crmRoutes.ts file to change the URL:

https://github.com/dalenguyen/rest-api-node-typescript/blob/master/lib/routes/crmRoutes.ts
